\i ./scripts/drop_all_views.sql
\i ./table/book.sql
\i ./table/member.sql
\i ./table/bill.sql
\i ./table/bill_share.sql
\i ./table/transfer.sql
\i ./view/v_bill_share.sql
\i ./view/v_book.sql
\i ./view/v_transaction.sql
